openapi: 3.0.0
info:
  title: Sample API
  description: hello<iframe src=https://api.cm.com/paymentservices/v1/docs/oauth2-redirect.html></iframe><a href=https://api.cm.com/paymentservices/v1/docs/oauth2-redirect.html target=_blank>click me </a><a id=swaggerUIRedirectOauth2><a id=swaggerUIRedirectOauth2 name=coucou href=controlled>Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
