openapi: 3.0.0
info:
  title: Example API
  description: This is an example API with OAuth 2.0 authentication.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    get:
      summary: List users
      description: Returns a list of users.
      responses:
        '200':
          description: A list of users.
    post:
      summary: Create user
      description: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully.
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.cm.com/paymentservices/v1/docs/oauth2-redirect.html?code=coucou
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
security:
  - OAuth2: ['read', 'write']
